### PR TITLE
fix: more typedefs improvements

### LINKED ISSUE #363: TypeScript types broken in ES Modules
It looks like **v0.7.1** has a TypeScript typings issue when used in an **ES Modules** project. The runtime API works, but the TypeScript types don’t match the runtime shape.

#### Summary
- In **v0.7.1**, when using **ESM**, the default import (`import iconv from "iconv-lite"`) is typed incorrectly: it **doesn’t expose the expected members** (e.g. `encode`, `decode`, etc.). As a result, TypeScript reports that `iconv.encode` / `iconv.decode` do not exist, even though they do at runtime.
- A type-only workaround is `iconv.default.encode()`, but it **fails at runtime** (`iconv.default` is `undefined`).

#### Environment
- `iconv-lite`: **0.7.1**
- TypeScript: **5.9.3**

#### Steps to reproduce
1. Create an ESM project (`package.json` includes `"type": "module"`):

package.json
```json
{
  "type": "module",
  "dependencies": {
    "iconv-lite": "0.7.1"
  },
  "devDependencies": {
    "typescript": "5.9.3"
  }
}
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es2016",
    "module": "node18",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  }
}
```

3. Install `iconv-lite@0.7.1`.
4. Add this code:
```ts
import iconv from "iconv-lite";

const input = "こんにちは";
const encoding = "shift_jis";

// Works at runtime, but TypeScript errors:
iconv.encode(input, encoding);

// The following PASSES typecheck but FAILS at runtime (iconv.default is undefined):
iconv.default.encode(input, encoding);
```

4. Run `tsc --noEmit`.

#### Actual result
TypeScript errors:

```
TS2339: Property 'encode' does not exist on type 'typeof iconv'.
```

#### Expected result
TypeScript should allow `iconv.encode(...)` and `iconv.decode(...)` for the default import, consistent with runtime behavior.

#### Additional notes
- If I change `iconv-lite` to **0.7.0**, the same ESM configuration typechecks successfully.
- If I keep **0.7.1** but switch the project to **CommonJS** (remove `"type": "module"`), it also typechecks.

### PR DESCRIPTION
**Pull request by plbstl**
Like in https://github.com/pillarjs/iconv-lite/pull/330#issuecomment-3651158261, the changes made in https://github.com/plbstl/iconv-lite/tree/more-typedefs-improvements resolves the issue.

Changing only the typings will not fully resolve the issue, as the JavaScript code will behave differently at runtime. The tests still pass, and were (technically) not modified.

You can see in <https://github.com/nodejs/cjs-module-lexer>'s README, that `module.exports`, `module.exports.x` and `exports.x` are shown. That's the right way to export CommonJS modules.

cc @bjohansebas @prigaux @takayukioda @kyota-fujikura @Nirator78 . Can you review and verify that these changes work in the different environments and configs?

Closes #363

### CODE REVIEW

**Comment by plbstl** [comment]
@kyota-fujikura Thank you very much for the feedback.

And you're right. Removing `export { iconv as default }` ensures the correct behavior (both `tsc` and runtime fail). I just pushed the relevant changes.

After cloning <https://github.com/kyota-fujikura/iconv-lite-type-error-reproduction>, I also added a `src/named-import.ts` file:

```ts
import { encode, decode } from "iconv-lite";

const input = "こんにちは";
const encoding = "shift_jis";

const encoded = encode(input, encoding);
const decoded = decode(encoded, encoding);

console.log({ encoded, decoded });
```

and scritps for running the files directly with NodeJS:

```json
"check-default-import-ts": "node src/default-import.ts",
"check-named-import-ts": "node src/named-import.ts",
"check-namespace-import-ts": "node src/namespace-import.ts"
```

They all worked as expected.

File: lib/index.js [hunk 1]
```diff
@@ -9,77 +9,77 @@ var iconv = module.exports
...
+  var decoder = exports.getDecoder(encoding, options)
 
   var res = decoder.write(buf)
   var trail = decoder.end()
 
   return trail ? (res + trail) : res
 }
 
-iconv.encodingExists = function encodingExists (enc) {
+exports.encodingExists = function encodingExists (enc) {
```
Comment (bjohansebas) [inline lib/index.js]: there's something that doesn't add up, and it's that technically with iconv.[nameOfObject] that's already being done, I can't understand why it doesn't work for TypeScript with the old way, but it does work with this new way, I feel like it's just a bug in attw that can't detect that rule properly

**Review by bjohansebas — APPROVED** [review]
LGTM. I’ll leave it open for a bit longer so more people can take a look, and I’ll try to release it in January
